name: CI - Biome and TypeScript
on:
  pull_request:
    
jobs:
  test:
    name: Biome & TypeScript
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          lfs: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Contentlayer
        run: bunx contentlayer2 build

      - name: Run TypeScript checks
        run: bunx tsc --noEmit

      - name: Run Biome check
        run: bunx biome ci .
